spring:
  application:
  name: OreumiWeek3

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurant
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        auto_quote_keyword: true
        format_sql: true
    generate-ddl: true

server:
  port: 8080
